apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: swastiajmera/myapp:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://admin:password@mongo-service:27017/mydb?authSource=admin
